# Generated by Django 5.1.1 on 2026-05-01 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_confirmation_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code_expiration_dttm',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 2, 0, 39, 24, 67395)),
        ),
    ]
