# Generated by Django 5.1.1 on 2026-05-01 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_confirmation_code_expiration_dttm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code_expiration_dttm',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 2, 3, 37, 38, 83047)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
