# Generated by Django 5.1.1 on 2026-05-02 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_confirmation_code_expiration_dttm_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('-date_joined',)},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code_expiration_dttm',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 2, 19, 28, 20, 746561)),
        ),
    ]
