# Generated by Django 5.1.1 on 2026-04-30 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_review_options_review_unique_review_per_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-pub_date', 'author')},
        ),
    ]
